### ISSUE TITLE
Shareable link

### ISSUE THREAD

**Issue by ghost** [ruud00000/bwa-u4-feature-request#1]
<img width="687" alt="screen shot 2017-09-07 at 10 50 19 am" src="https://user-images.githubusercontent.com/7355203/30169428-62859208-93ba-11e7-9e10-1abc432b6f66.png">

https://drive.google.com/open?id=1YSjcza14ngPlj8GnwnZeRVwYRHwB1GIdgltn6aKzO10

Your technical design document should be shareable, otherwise it can't be reviewed. Please let us know when you've corrected this.

**Comment by ruud00000** [comment]
done
